# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b8d3832a8fb5d1ba12131f1ada21354718c7269b2b15c89a0c42865dd2afb521bed7d3a0a5d2517c95582a1508ddd78ed66addad7466119cc9c9caccec7235b

test:
  secret_key_base: 8ff3afe49bdf1a9e4e656c0943537c8a8782dac87676869fc19922f46c62bc5230d415e72bd9b4390f5032ae7fc755c91427bc68853c5a3c066c6104bf9dad5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
